1
hxnchar/lab3Web pull request #1
Opened 2021-11-28 20:12 UTC by hxnchar

2021-12-29 22:47 UTC, nosovk commented
<img width="916" alt="image" src="https://user-images.githubusercontent.com/1398808/147708815-16ee8d9a-d5c9-4305-a9ee-a31346933e86.png">
не работает

2021-12-29 22:49 UTC, nosovk commented on src/helper/request-helper.js
> +      console.error(errors);
обработать ошибки?

2021-12-29 22:49 UTC, nosovk commented on scripts/setupTypeScript.js
> +// @ts-check
если не используется - удаляй

2021-12-31 15:27 UTC, nosovk commented on src/App.svelte
> +      document.getElementById("errorLabel").textContent = "Помилка";
это прямо совсем не svelte way. У свелта есть bind для привязки dom елемента к переменной. Но конкретно тут можно воспользоваться либо контекстом либо сторами

2021-12-31 15:29 UTC, nosovk commented
<img width="909" alt="image" src="https://user-images.githubusercontent.com/1398808/147830492-f034c0f5-0011-42b8-85d7-9f318587a8f7.png">
все равно падает

2022-01-06 11:46 UTC, DanielJorn requested changes

2022-01-06 11:46 UTC, DanielJorn commented on package.json
> +    "eslint:check": "eslint .",
ІГНОР ПАС НЕ ТРЕБА ТУТ??????

2022-01-06 11:46 UTC, DanielJorn commented on package.json
> +    "stylelint-config-recommended-scss": "^5.0.2",
DEV DEPENDENCY

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +      uri: "wss://labaa3.herokuapp.com/v1/graphql",
ENV

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +      {#each $debtorsArray.data.debtors as debtor}
svelte each keyed
https://svelte.dev/tutorial/keyed-each-blocks

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +    let newDebtorArr = [];
масивы и обьекты всегда const

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +    let newDebtorArr = [];
const  newDebtorArr = document
      .getElementById("newDebtorInputbox")
      .value.split(" ")

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +    <input id="newDebtorInputbox" />
```
svelte bind value 
https://svelte.dev/tutorial/bind-this
буде шось типу такого:
<js>
const newDeptorInfo = {}

const {name,surname,money} = newDeptorInfo;
await request(name,surname,money);
</js>

<html>
<input bind:value={newDeptorInfo.name} />
<input bind:value={newDeptorInfo.surname} />
<input bind:value={newDeptorInfo.money} />
</html>

```

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +      errorMSG.update(n => (n = "Помилка"));
errorMSG.set("Помилка")

2022-01-06 11:46 UTC, DanielJorn commented on src/App.svelte
> +    await http.startExecuteMyMutation(Queries.DeleteNegative());
обработка ошибок7?!?!?

2022-01-06 11:46 UTC, DanielJorn commented on src/helper/request-helper.js
> +  API_URL = "https://labaa3.herokuapp.com/v1/graphql";
env

2022-01-06 11:46 UTC, DanielJorn commented on src/helper/request-helper.js
> +      console.error(errors);
throw new Error(errors[0].message)

2022-01-06 11:47 UTC, DanielJorn commented
loading when request is sent

2022-01-07 17:45 UTC, Ekedani commented on src/helper/request-helper.js
> +    const result = await fetch(this.API_URL, {
**Возможно**, лучше переписать через .then(), поскольку тут обработки ошибок нет. Можешь глянуть как у меня это сделано

2022-01-08 14:57 UTC, nosovk commented on src/App.svelte
> +  loadersCount.subscribe(value => {
можно использовать его напрямую в svelte файлах
$loadersCount эквивалентно тому что тут написанно тут с subscribe в другую переменную

2022-01-08 14:58 UTC, nosovk commented on src/App.svelte
> +      loadersCount.update(n => n - 1);
$loadersCount++
даст такой же еффект Нужно только помнить что это только в .svelte файлах работает

2022-01-08 14:59 UTC, nosovk commented on src/App.svelte
> +      errorMSG.set("Error occurred: " + e.message);
$errorMSG можно испоьзовать как store тоже

2022-01-08 15:00 UTC, nosovk commented on src/App.svelte
> +        {#each $debtorsArray.data.debtors as debtor (debtor.id)}
нужно еще проверять debtors.lengh есть (если нет показывать заглушку что тут нет записей)

2022-01-08 15:02 UTC, nosovk commented on src/App.svelte
> +      style="visibility:{countLoaders > 0 ? 'visible' : 'hidden'}"
реализовать через 
```css
.hidden {
visibility:hidden
}
```
и `class:hidden={$loadersCount}`

2022-01-08 15:02 UTC, nosovk commented on src/helper/request-helper.js
> +  async fetchGraphQL(operationsDoc, operationName, variables) {
не понятно зачем тут указание async

2022-01-08 15:04 UTC, nosovk commented on src/helper/requests.js
> +  static InsertRecord = (surname, name, debt) => `
подстановка через интерполяцию не делает санитизацию данных, лушче gql и обьект с ключами для подстановки

2022-01-10 18:57 UTC, nosovk commented on src/App.svelte
> +      {#if $debtorsArray.data.debtors.length == 0}
тут наверное нужно ===?

2022-01-12 20:57 UTC, hxnchar commented
https://lab3-web.vercel.app/

2022-01-13 08:42 UTC, hxnchar commented
https://lab3-web.vercel.app/

2022-01-13 09:56 UTC, hxnchar commented
https://lab3-web.vercel.app/

2022-01-13 10:00 UTC, nosovk commented on src/App.svelte
> +    isOnline.set(false);
isOnline это store
вопроса два
1. для store можно написать $isOnline=false
2. этот стор не используется за пределами app,svelte, почему просто локальную переменную не использовать тогда?

2022-01-13 10:02 UTC, nosovk commented on src/App.svelte
> +    $loadersCount++;
Следующая проверка синхронная в отличие от fetch, то есть мы можем просто поставить $loadersCount++ после нее, убрать лишние проверки и т.п., а результат не поменяется

2022-01-13 10:03 UTC, nosovk commented on src/App.svelte
> +  function resetValues() {
https://developer.mozilla.org/ru/docs/Web/API/HTMLFormElement/reset
кроме того у инпутов есть дефолтные значения

2022-01-13 10:03 UTC, hxnchar commented on src/App.svelte
> +    isOnline.set(false);
это старая версия
я только что фиксил это

2022-01-13 10:04 UTC, nosovk commented on src/App.svelte
> +    $loadersCount++;
вместо того чтобы вставлять эту логику в каждом методе, может лучше ее разово в executeMyMutation описать?

2022-01-13 11:05 UTC, hxnchar commented on src/App.svelte
> +    $loadersCount++;
executeMyMutation не используется

2022-01-13 11:12 UTC, hxnchar commented on src/App.svelte
> +  function resetValues() {
чуть по-другому пофиксил

2022-01-13 11:20 UTC, hxnchar commented
https://lab3-web.vercel.app/

2022-01-13 12:47 UTC, hxnchar commented
https://lab5-web.vercel.app/

2022-01-14 13:24 UTC, merged